POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "full_names": "IRUMVA Anselme",
  "username": "anacoder.second",
  "email": "kalisa.augustin@gmail.com",
  "title": "Student at Rwanda Coding Academy",
  "bio": "Holla Mucho gusto",
  "password": "Kirehe123",
  "phone": "784565234",
  "user_type": "VENDOR"
}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "login": "kalisa.augustin@gmail.com",
  "password": "Kirehe123"
}