DELETE http://localhost:3000/api/services/60c3b511b52dd08be2880cb0
Accept: application/json

###

GET http://localhost:3000/api/services
Content-Type: application/json

{
  "name": "Updated Health care",
  "description": "Updated A very cool description",
  "icon": "Updated No Icon"
}