GET http://localhost:3000/api/services
Accept: application/json

###

POST http://localhost:3000/api/services
Content-Type: application/json

{
  "name": "Health care",
  "description": "A very cool description",
  "icon": "No Icon"
}